name: Ghost App Deployment

on:
  push:
    branches:
      - main  # Trigger only on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies from the current version folder
      - name: Install Dependencies (Current)
        working-directory: ghost-app/current
        run: npm install

      # (Optional) Build the app if necessary
      - name: Build App (Current)
        working-directory: ghost-app/current
        run: npm run build

      # Deploy to Vercel using the current folder
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --name "ghost-app-current"
