name: Ghost App Deployment

on:
  push:
    branches:
      - main  # Trigger only on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # - name: Install Ghost CLI
      #   run: npm install -g ghost-cli

      # - name: Install Dependencies (Current)
      #   working-directory: current
      #   run: ghost install

      # Build asset files
      - name: Build Assets
        working-directory: current
        run: npm run build:assets

      # Compile TypeScript files
      - name: Compile TypeScript
        working-directory: current
        run: npm run build:tsc

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --name "ghost-app"
